apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-internal-tls
  namespace: observability
spec:
  secretName: grafana-tls
  dnsNames:
    - "grafana.{{ .Values.baseDomain }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer