apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-internal-tls
  namespace: kube-system
spec:
  secretName: traefik-dashboard-tls
  dnsNames:
    - "traefik.{{ .Values.baseDomain }}"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer