apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`traefik.{{ .Values.baseDomain }}`)
    middlewares:
      - name: internal-whitelist
        namespace: kube-system
      - name: https-redirect
        namespace: kube-system
    priority: 10
    services:
    - name: traefik-dashboard
      port: 9000