apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-whitelist
  namespace: kube-system
spec:
  ipAllowList:
    sourceRange:
    {{- range .Values.traefik.localIPWhiteList }}
      - {{ . }}
    {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true