apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-internal-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - "argocd.{{ .Values.baseDomain }}"
  issuerRef:
    {{- if .Values.useSelfSigned }}
    name: ca-issuer
    {{- else }}
    name: acme
    {{- end }}
    kind: ClusterIssuer