apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.{{ .Values.baseDomain }}`)
    priority: 10
    middlewares:
      - name: internal-whitelist
        namespace: kube-system
      - name: https-redirect
        namespace: kube-system
    services:
      - name: argocd-server
        port: 80
  tls:
    secretName: argocd-tls