apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`longhorn.{{ .Values.baseDomain }}`)
    middlewares:
      - name: internal-whitelist
        namespace: kube-system
      - name: https-redirect
        namespace: kube-system
    priority: 10
    services:
      - name: longhorn-frontend
        port: 80