apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-default
  namespace: longhorn-system
spec:
  cron: "0 4 1 * *"
  task: "backup"
  groups:
  - default
  retain: 1
  concurrency: 2
