apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`esphome.{{ .Values.esphome.hostname }}`)
    middlewares:
      - name: internal-whitelist
        namespace: kube-system
      - name: https-redirect
        namespace: kube-system
    priority: 10
    services:
      - name: {{ .Release.Name }}
        port: {{ .Values.service.listenPort }}
  tls:
    secretName: {{ .Release.Name }}-tls
