apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-acme
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
    - "home.cybercarlitos.xyz"
  issuerRef:
    name: acme
    kind: Issuer