apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
  - "ReadWriteMany"
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi