apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - "ReadWriteMany"
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi