apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`argocd.pi-master-1.local`)
    priority: 10
    services:
      - name: argocd-server
        port: 80